"""Vendored ShinrAI PII inference runtime — generated by shinrai-pii-bert's
scripts/vendor-bert.sh. Never edit by hand; regenerate from the source repo.
Torch-free: needs only onnxruntime, numpy, transformers (tokenizer), pyyaml.
"""

from .adapter import (  # noqa: F401
    DEFAULT_CONFIDENCE_THRESHOLD,
    merge_person_spans,
    to_legacy_entities,
)
from .onnx_numpy import NumpyOnnxPredictor  # noqa: F401
